
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\acer\Desktop\shoppingcarta\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1367x767")
window.configure(bg = "#9DCD5A")


canvas = Canvas(
    window,
    bg = "#9DCD5A",
    height = 767,
    width = 1367,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    836.0,
    227.0,
    1334.0,
    520.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    123.0,
    181.0,
    519.0,
    554.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    459.0,
    15.0,
    1004.0,
    161.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=800.0,
    y=615.0,
    width=524.0,
    height=81.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=104.0,
    y=611.0,
    width=425.0,
    height=75.0
)
window.resizable(False, False)
window.mainloop()
