
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import sqlite3

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,Toplevel,Frame,Label


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\acer\Desktop\Investhub\build\assets\frame0")
DATABASE_PATH = "aryan.db"

def create_database():
    conn = sqlite3.connect(DATABASE_PATH)
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS users
                 (group_id INTEGER, user_id INTEGER, user_name TEXT)''')
    conn.commit()
    conn.close()


def open_new_window():
    new_window = Toplevel(window)
    new_window.geometry("800x600")  # Adjust the window size as needed
    new_window.title("New Page")

    conn = sqlite3.connect(DATABASE_PATH)
    c = conn.cursor()
    c.execute("SELECT * FROM users")
    data = c.fetchall()
    conn.close()

    # Create a frame to contain the labels
    frame = Frame(new_window)
    frame.pack(padx=20, pady=20)  # Adjust padding as needed

    # Display labels for the entries
    label_texts = ["GROUP ID", "USER ID", "USER NAME"]
    for i, label_text in enumerate(label_texts):
        label = Label(frame, text=label_text, fg="black", font=("Poppins Regular", 18))
        label.grid(row=0, column=i, padx=5, pady=5)

    # Display data from the database
    for i, row in enumerate(data):
        for j, value in enumerate(row):
            label = Label(frame, text=value, fg="black", font=("Poppins Regular", 18))
            label.grid(row=i+1, column=j, padx=5, pady=5)

    new_window.mainloop()

def save_and_open():
    group_id = entry_1.get()
    user_id = entry_2.get()
    user_name = entry_3.get()

    # Save data to the database
    conn = sqlite3.connect(DATABASE_PATH)
    c = conn.cursor()
    c.execute("INSERT INTO users (group_id, user_id, user_name) VALUES (?, ?, ?)", (group_id, user_id, user_name))
    conn.commit()
    conn.close()

    # Open new window to display saved data
    open_new_window()

    

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

create_database()

window = Tk()

window.geometry("1366x768")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 768,
    width = 1366,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    12.0,
    1366.0,
    780.0,
    fill="#FFFFFF",
    outline="")
background_image = PhotoImage(file=relative_to_assets(r"c:\Users\acer\Downloads\grpshoppingedited (1).png"))
canvas.create_image(0, 0, anchor='nw', image=background_image)

canvas.create_text(
    740.0,
    332.0,
    anchor="nw",
    text="GROUP ID",
    fill="#000000",
    font=("Poppins Regular", 36 * -1)
)

canvas.create_text(
    740.0,
    417.0,
    anchor="nw",
    text="USER ID",
    fill="#000000",
    font=("Poppins Regular", 36 * -1)
)

canvas.create_text(
    740.0,
    502.0,
    anchor="nw",
    text="USER NAME",
    fill="#000000",
    font=("Poppins Regular", 36 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1122.5,
    363.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Poppins Regular", 18)
)
entry_1.place(
    x=991.5,
    y=339.0,
    width=262.0,
    height=47.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1122.5,
    441.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Poppins Regular", 18)
)
entry_2.place(
    x=991.5,
    y=417.0,
    width=262.0,
    height=47.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1122.5,
    534.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0,
    font=("Poppins Regular", 18)
)
entry_3.place(
    x=991.5,
    y=510.0,
    width=262.0,
    height=47.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=save_and_open, 
    relief="flat"
)
button_1.place(
    x=895.0,
    y=602.0,
    width=302.0,
    height=81.0
)
window.resizable(False, False)
window.mainloop()
